### ISSUE TITLE
Buttons render incorrectly when controls out of order

### ISSUE THREAD

**Issue by joshbenner** [jamesridgway/devdeck#8]
Buttons occasionally render incorrectly, showing the wrong content as well as render artifacts. This seems to be related to listing the controls out of order, as the behavior can be prevented by ordering the keys in the configuration.

![devdeck-artifacts](https://user-images.githubusercontent.com/79151/123550239-aae2d700-d73a-11eb-8e9a-c2cb8a039b4f.png)

Configuration producing this behavior:
```yaml
decks:
- name: devdeck.decks.single_page_deck_controller.SinglePageDeckController
  serial_number: redacted
  settings:
    controls:
    - key: 0
      name: devdeck_slack.slack_deck.SlackDeck
      settings:
        api_key: 'redacted'
        actions:
          - action: online
            key: 0
          - action: away
            key: 1
          - action: status
            key: 2
            text: BRB
            emoji: ':stopwatch:'
    - key: 7
      name: devdeck.controls.clock_control.ClockControl
    - key: 1
      name: devdeck.controls.timer_control.TimerControl
```
